version: '3.8'
name: betflix

services:
  service-registry:
    container_name: service-registry
    image: quangkhanh288/service-registry
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8761:8761"
    networks:
      - betflix-network
  user-service:
    container_name: user-service
    image: quangkhanh288/user-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MOVIE_HOSTNAME: movie-service
    ports:
      - "8092:8092"
    networks:
      - betflix-network
  gateway-service:
    container_name: gateway-service
    image: quangkhanh288/gateway-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "9091:9091"
    networks:
      - betflix-network
  movie-service:
    container_name: movie-service
    image: quangkhanh288/movie-service
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8091:8091"
    networks:
      - betflix-network
  order-service:
    container_name: order-service
    image: quangkhanh288/order-service
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: prod
      MOVIE_HOSTNAME: movie-service
      USER_HOSTNAME: user-service
    ports:
      - "8093:8093"
    networks:
      - betflix-network
  config-server:
    container_name: config-server
    image: quangkhanh288/config-server
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8888:8888"
    networks:
      - betflix-network
  email-service:
    container_name: email-service
    env_file:
      - "./email-service/email-service/.env"
    image: quangkhanh288/email-service
    restart: unless-stopped
    environment:
      RABBITMQ_HOSTNAME: betflix-rabbitmq
    ports:
      - "8095:8095"
    networks:
      - betflix-network
networks:
  betflix-network:
    external: true
