
name: Java CI order-service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'order-service/order-service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'order-service/order-service/**'


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./order-service/order-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build and push docker image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: order-service/order-service
          push: true
          tags: quangkhanh288/order-service:latest